version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: mvn test
      - store_artifacts:
          path:  target
      - run:
          name: Upload to Codecov
          command: bash <(curl -s https://codecov.io/bash)
